version: "3.8"
services:
  dbpostgres:
    image: library/postgres:13.2-alpine
    container_name: pgdb-docker-hamster
    #    restart: always
    environment:
      - POSTGRES_DB=hamstershort
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dbpw
    ports:
      - 8082:5432
    volumes:
      - ./postgres/storage:/var/lib/postgresql/data
